# Generated by Django 3.2.5 on 2021-08-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('objectif', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('pedagogic_aims', models.TextField()),
                ('victory_celebration_display', models.TextField()),
                ('publication_date', models.DateTimeField()),
                ('edition_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'article',
                'managed': True,
            },
        ),
    ]
