# Generated by Django 3.2.5 on 2021-08-01 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ArticlesApp', '0001_initial'),
        ('UsersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id_equipment', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=150)),
                ('quantity', models.FloatField()),
                ('unity', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'equipment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('imagefield', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=70, null=True)),
                ('authors', models.CharField(blank=True, max_length=60, null=True)),
                ('title', models.CharField(blank=True, max_length=70, null=True)),
                ('image_article', models.ImageField(blank=True, null=True, upload_to='article_image/')),
            ],
            options={
                'db_table': 'image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id_video', models.AutoField(primary_key=True, serialize=False)),
                ('videofield', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=70)),
                ('authors', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=70)),
                ('video_article', models.FileField(blank=True, null=True, upload_to='article_video/')),
            ],
            options={
                'db_table': 'video',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('account_author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='UsersApp.account')),
                ('bibliography', models.ManyToManyField(to='ArticlesApp.Article')),
            ],
            options={
                'db_table': 'author',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='id_badge',
            field=models.ForeignKey(db_column='id_badge', on_delete=django.db.models.deletion.DO_NOTHING, to='UsersApp.badge'),
        ),
        migrations.AddField(
            model_name='article',
            name='list_equipement',
            field=models.ManyToManyField(to='ArticlesApp.Equipment'),
        ),
        migrations.AddField(
            model_name='article',
            name='list_image',
            field=models.ManyToManyField(to='ArticlesApp.Image'),
        ),
        migrations.AddField(
            model_name='article',
            name='list_video',
            field=models.ManyToManyField(to='ArticlesApp.Video'),
        ),
    ]
