# Generated by Django 3.2.5 on 2021-08-15 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0002_alter_badge_image_badge'),
        ('ArticlesApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id_badge',
            field=models.ForeignKey(db_column='id_badge', on_delete=django.db.models.deletion.CASCADE, to='UsersApp.badge'),
        ),
    ]
