# Generated by Django 3.2.5 on 2021-09-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticlesApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_cover_image',
            field=models.ImageField(blank=True, default='ex-par-nat_logo.png', null=True, upload_to='article_cover_image/'),
        ),
    ]
