# Generated by Django 3.2.5 on 2021-09-11 12:45

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id_badge', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=60)),
                ('level', models.IntegerField()),
                ('image_badge', models.ImageField(blank=True, default='ex-par-nat_logo.png', null=True, upload_to='badge_image/')),
            ],
            options={
                'db_table': 'badge',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_account', models.AutoField(primary_key=True, serialize=False)),
                ('is_tribut', models.BooleanField(default=False)),
                ('is_author', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'account',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tribut',
            fields=[
                ('account_tribut', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='UsersApp.account')),
            ],
            options={
                'db_table': 'tribut',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('id_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('tutor_username', models.CharField(max_length=70)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_jointed', models.DateTimeField(auto_now_add=True)),
                ('is_author', models.BooleanField(null=True)),
                ('image_profile_tutor', models.ImageField(blank=True, default='elephant.jpeg', null=True, upload_to='profile_image/')),
                ('account_tribut', models.ForeignKey(db_column='account_tribut_id', on_delete=django.db.models.deletion.DO_NOTHING, to='UsersApp.tribut')),
            ],
            options={
                'db_table': 'tutor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id_child', models.AutoField(primary_key=True, serialize=False)),
                ('child_username', models.CharField(max_length=70)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_jointed', models.DateTimeField(auto_now_add=True)),
                ('image_profile_child', models.ImageField(blank=True, default='elephant.jpeg', null=True, upload_to='profile_image/')),
                ('trophies', models.ManyToManyField(blank=True, to='UsersApp.Badge')),
                ('account_tribut', models.ForeignKey(db_column='account_tribut_id', on_delete=django.db.models.deletion.DO_NOTHING, to='UsersApp.tribut')),
            ],
            options={
                'db_table': 'child',
                'managed': True,
            },
        ),
    ]
